name: build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config --global user.name "CI Bot"
          git config --global user.email "ci-bot@example.com"
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-$cache_id
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install -r requirements.txt
      - run: echo "docs_version=$(cat version.txt)" >> $GITHUB_ENV
      - name: Tag commit
        id: tag-commit
        run: |
          git tag "$docs_version" "${{github.ref_name}}"
          git push origin "$version" || true
      - name: Build Docs
        run: |
          git fetch origin gh-pages
          mike deploy --push --update-aliases $docs_version latest

  trigger:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Trigger publish
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: publish-trigger
