name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pages: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config --global user.name "CI Bot"
          git config --global user.email "ci-bot@example.com"
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-$cache_id
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install -r requirements.txt
      - run: echo "docs_version=$(cat version.txt)" >> $GITHUB_ENV
      - name: Build Docs
        run: |
          git fetch origin gh-pages
          mike deploy --push -update-aliases $docs_version latest
